project:
  type: book

book:
  title: "Feature Engineering A-Z"
  author: "Emil Hvitfeldt"
  date: "9/14/2021"
  sidebar:
    style: "floating"
    search: true
  chapters:
    - index.qmd # v1
    - introduction.qmd # v1
    - motivation.qmd
    - modeling.qmd
    - how-to-deal-with.qmd # v1
    - part: "Numeric Features"
      chapters:
        - numeric.qmd # v1
        - numeric-logarithms.qmd # v1
        - numeric-sqrt.qmd # v1
        - numeric-boxcox.qmd # v1
        - numeric-yeojohnson.qmd # v1
        - numeric-percentile.qmd # v1
        - numeric-normalization.qmd # v1
        - numeric-range.qmd # v1
        - numeric-maxabs.qmd # v1
        - numeric-robust.qmd # v1
        - numeric-binning.qmd # v1
        - numeric-splines.qmd # v1
        - numeric-polynomial.qmd # v1
    - part: "Categorical Features"
      chapters:
        - categorical.qmd # v1
        - categorical-cleaning.qmd # v1
        - categorical-unseen.qmd # v1
        - categorical-dummy.qmd # v1
        - categorical-label.qmd # v1
        - categorical-ordinal.qmd # v1
        - categorical-binary.qmd # v1
        - categorical-frequency.qmd # v1
        - categorical-target.qmd # Progress
        - categorical-hashing.qmd # v1
        - categorical-leaveoneout.qmd
        - categorical-leaf.qmd
        - categorical-glmm.qmd
        - categorical-catboost.qmd
        - categorical-woe.qmd
        - categorical-jamesstein.qmd
        - categorical-mestimator.qmd
        - categorical-thermometer.qmd
        - categorical-quantile.qmd
        - categorical-summary.qmd
        - categorical-multi-dummy.qmd
        - categorical-collapse.qmd
        - categorical-combination.qmd
    - part: "Datetime Features"
      chapters:
        - datetime.qmd # v1
        - datetime-extraction.qmd # Progress
        - datetime-advanced.qmd
        - datetime-circular.qmd
    - part: "Text Features"
      chapters:
        - text.qmd # v1
        - text-manual.qmd
        - text-cleaning.qmd
        - text-tokenization.qmd
        - text-stemming.qmd
        - text-ngrams.qmd
        - text-stopwords.qmd
        - text-filter.qmd
        - text-tf.qmd
        - text-tfidf.qmd
        - text-hashing.qmd
        - text-onehot.qmd
        - text-lda.qmd
        - text-word2vec.qmd
        - text-bert.qmd
    - part: "Circular Features"
      chapters:
        - circular.qmd # v1
        - circular-trig.qmd
        - circular-splines.qmd
        - circular-indicators.qmd
    - part: "Missing Data"
      chapters:
        - missing.qmd # v1
        - missing-simple.qmd
        - missing-model.qmd
        - missing-indicator.qmd
        - missing-remove.qmd
    - part: "Too Many Variables"
      chapters:
        - too-many.qmd # v1
        - too-many-zv.qmd
        - too-many-pca.qmd
        - too-many-pca-variants.qmd
        - too-many-ica.qmd
        - too-many-nmf.qmd
        - too-many-lda.qmd
        - too-many-gda.qmd
        - too-many-autoencoder.qmd
        - too-many-umap.qmd
        - too-many-isomap.qmd
        - too-many-filter.qmd
        - too-many-wrapper.qmd
        - too-many-embedded.qmd
    - part: "Correlated Data"
      chapters:
        - correlated.qmd # v1
        - correlated-filter.qmd
    - part: "Outliers"
      chapters:
        - outliers.qmd # v1
        - outliers-remove.qmd
        - outliers-imputation.qmd
        - outliers-indicate.qmd
    - part: "Imbalanced Data"
      chapters:
        - imbalenced.qmd # v1
        - imbalenced-upsample.qmd
        - imbalenced-rose.qmd
        - imbalenced-smote.qmd
        - imbalenced-smote-variants.qmd
        - imbalenced-borderline-smote.qmd
        - imbalenced-adasyn.qmd
        - imbalenced-downsample.qmd
        - imbalenced-nearmiss.qmd
        - imbalenced-tomek.qmd
        - imbalenced-cnn.qmd
        - imbalenced-enn.qmd
        - imbalenced-hardness-threshold.qmd
        - imbalenced-one-sided.qmd
    - part: "Miscellaneous"
      chapters:
        - miscellaneous.qmd # v1
        - miscellaneous-id.qmd
        - miscellaneous-color.qmd
        - miscellaneous-zipcodes.qmd
        - miscellaneous-email.qmd
    - part: "Spatial"
      chapters:
        - spatial.qmd # v1
        - spatial-distance.qmd
        - spatial-nearest.qmd
        - spatial-count.qmd
        - spatial-query.qmd
        - spatial-embedding.qmd
        - spatial-characteristics.qmd
    - part: "Time-Series Data"
      chapters:
        - time-series.qmd # v1
        - time-series-smooth.qmd
        - time-series-sliding.qmd
        - time-series-log-interval.qmd
        - time-series-missing.qmd
        - time-series-outliers.qmd
        - time-series-diff.qmd
        - time-series-lag.qmd
        - time-series-rolling-window.qmd
        - time-series-expanding-window.qmd
        - time-series-fourier.qmd
        - time-series-wavelet.qmd
    - part: "Image Data"
      chapters:
        - image.qmd # v1
        - image-edge-corner.qmd
        - image-texture.qmd
        - image-grayscale.qmd
        - image-colors.qmd
        - image-noise.qmd
        - image-normalization.qmd
        - image-resize.qmd
        - image-brightness.qmd
        - image-shift-flip-rotate.qmd
        - image-crop-scale.qmd
        - image-embeddings.qmd
    - part: "Ralational Data"
      chapters:
        - relational.qmd # v1
        - relational-manual.qmd
        - relational-auto.qmd
    - part: "Video Data"
      chapters:
        - video.qmd
        - video-tmp.qmd
    - part: "Sound Data"
      chapters:
        - sound.qmd
        - sound-tmp.qmd
    - order.qmd
    - sparse.qmd
    - models.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
    toc-depth: 1
