project:
  type: book

book:
  title: "Feature Engineering A-Z"
  author: "Emil Hvitfeldt"
  date: "9/14/2021"
  sidebar:
    style: "floating"
    search: true
  chapters:
    - index.qmd
    - introduction.qmd
    - motivation.qmd
    - modeling.qmd
    - how-to-deal-with.qmd
    - part: "Numeric Features"
      chapters:
        - numeric.qmd
        - numeric-logarithms.qmd
        - numeric-sqrt.qmd
        - numeric-boxcox.qmd
        - numeric-yeojohnson.qmd
        - numeric-percentile.qmd
        - numeric-normalization.qmd
        - numeric-range.qmd
        - numeric-maxabs.qmd
        - numeric-robust.qmd
        - numeric-splines.qmd # Progress
        - numeric-polynomial.qmd
    - part: "Categorical Features"
      chapters:
        - categorical.qmd
        - categorical-cleaning.qmd
        - categorical-unseen.qmd
        - categorical-dummy.qmd
        - categorical-label.qmd
        - categorical-ordinal.qmd
        - categorical-binary.qmd
        - categorical-frequency.qmd
        - categorical-target.qmd # Progress
        - categorical-hashing.qmd
        - categorical-leaveoneout.qmd
        - categorical-leaf.qmd
        - categorical-glmm.qmd
        - categorical-catboost.qmd
        - categorical-woe.qmd
        - categorical-jamesstein.qmd
        - categorical-mestimator.qmd
        - categorical-thermometer.qmd
        - categorical-quantile.qmd
        - categorical-summary.qmd
        - categorical-multi-dummy.qmd
        - categorical-collapse.qmd
        - categorical-combination.qmd
    - part: "Imbalanced Data"
      chapters:
        - imbalenced.qmd
        - imbalenced-smote.qmd
    - part: "Missing Data"
      chapters:
        - missing.qmd
        - missing-imputation.qmd
    - part: "Too Many Variables"
      chapters:
        - too-many.qmd
        - too-many-pca.qmd
    - part: "Outliers"
      chapters:
        - outliers.qmd
        - outliers-remove.qmd
    - part: "Datetime Features"
      chapters:
        - datetime.qmd
        - datetime-holiday.qmd
    - part: "Text Features"
      chapters:
        - text.qmd
        - text-tfidf.qmd
    - part: "Image Features"
      chapters:
        - image.qmd
        - image-stats.qmd
    - part: "Circular Features"
      chapters:
        - circular.qmd
        - circular-trig.qmd
    - part: "Time-Series Data"
      chapters:
        - time-series.qmd
        - time-series-fourier.qmd
    - part: "Correlated Data"
      chapters:
        - correlated.qmd
        - correlated-filter.qmd
    - part: "Miscellaneous"
      chapters:
        - miscellaneous.qmd
        - miscellaneous-zipcodes.qmd
    - part: "Video Data"
      chapters:
        - video.qmd
        - video-tmp.qmd
    - part: "Sound Data"
      chapters:
        - sound.qmd
        - sound-tmp.qmd
    - part: "Spatial"
      chapters:
        - spatial.qmd
        - spatial-gps.qmd
    - part: "Geospatial"
      chapters:
        - geospatial.qmd
        - geospatial-shapefiles.qmd
    - part: "Ralational Data"
      chapters:
        - relational.qmd
        - relational-tmp.qmd
    - order.qmd
    - sparse.qmd
    - models.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
