project:
  type: book

book:
  title: "Feature Engineering A-Z"
  author: "Emil Hvitfeldt"
  date: "9/14/2021"
  chapters:
    - index.qmd
    - introduction.qmd
    - motivation.qmd
    - modeling.qmd
    - how-to-deal-with.qmd
    - part: numeric.qmd
      chapters:
        - numeric-logarithms.qmd
        - numeric-sqrt.qmd
        - numeric-boxcox.qmd
        - numeric-yeojohnson.qmd
        - numeric-normalization.qmd
        - numeric-range.qmd
        - numeric-minabs.qmd
        - numeric-robust.qmd
        - numeric-splines.qmd
        - numeric-polynomial.qmd
    - part: categorical.qmd
      chapters:
        - categorical-dummy.qmd
        - categorical-label.qmd
        - categorical-binary.qmd
        - categorical-ordinal.qmd
        - categorical-frequency.qmd
        - categorical-helmert.qmd
        - categorical-difference.qmd
        - categorical-target.qmd
        - categorical-impact.qmd
        - categorical-polynomial.qmd
        - categorical-sum.qmd
        - categorical-hashing.qmd
        - categorical-leaveoneout.qmd
        - categorical-leaf.qmd
        - categorical-glmm.qmd
        - categorical-randomforest.qmd
        - categorical-catboost.qmd
        - categorical-woe.qmd
        - categorical-jamesstein.qmd
        - categorical-mestimator.qmd
        - categorical-thermometer.qmd
        - categorical-quantile.qmd
        - categorical-summary.qmd
        - categorical-collapse.qmd
        - categorical-multi-dummy.qmd
    - part: imbalenced.qmd
      chapters:
        - imbalenced-smote.qmd
    - part: missing.qmd
      chapters:
        - missing-imputation.qmd
    - part: too-many.qmd
      chapters:
        - too-many-pca.qmd
    - part: outliers.qmd
      chapters:
        - outliers-remove.qmd
    - part: datetime.qmd
      chapters:
        - datetime-holiday.qmd
    - part: text.qmd
      chapters:
        - text-tfidf.qmd
    - part: image.qmd
      chapters:
        - image-stats.qmd
    - part: circular.qmd
      chapters:
        - circular-trig.qmd
    - part: time-series.qmd
      chapters:
        - time-series-fourier.qmd
    - part: correlated.qmd
      chapters:
        - correlated-filter.qmd
    - part: miscellaneous.qmd
      chapters:
        - miscellaneous-zipcodes.qmd
    - part: video.qmd
      chapters:
        - video-tmp.qmd
    - part: sound.qmd
      chapters:
        - sound-tmp.qmd
    - order.qmd
    - sparse.qmd
    - models.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png

