project:
  type: book

book:
  title: "Feature Engineering A-Z"
  author: "Emil Hvitfeldt"
  date: "2024-01-28"
  repo-url: https://github.com/EmilHvitfeldt/feature-engineering-az
  site-url: https://example.com
  open-graph: true
  repo-actions: [edit, issue, source]
  sidebar:
    style: "docked"
    search: true
  chapters:
    - index.qmd # draft
    - introduction.qmd # draft
    - part: "Numeric Features"
      chapters:
        - numeric.qmd # draft
        - numeric-logarithms.qmd # draft
        - numeric-sqrt.qmd # draft
        - numeric-boxcox.qmd # draft
        - numeric-yeojohnson.qmd # draft
        - numeric-percentile.qmd # draft
        - numeric-normalization.qmd # draft
        - numeric-range.qmd # draft
        - numeric-maxabs.qmd # draft
        - numeric-robust.qmd # draft
        - numeric-binning.qmd # draft
        - numeric-splines.qmd # draft
        - numeric-polynomial.qmd # draft
        - numeric-arithmetic.qmd # draft
    - part: "Categorical Features"
      chapters:
        - categorical.qmd # draft
        - categorical-cleaning.qmd # draft
        - categorical-unseen.qmd # draft
        - categorical-dummy.qmd # draft
        - categorical-label.qmd # draft
        - categorical-ordinal.qmd # draft
        - categorical-binary.qmd # draft
        - categorical-frequency.qmd # draft
        - categorical-target.qmd # draft
        - categorical-hashing.qmd # draft
        - categorical-leaveoneout.qmd # draft
        - categorical-leaf.qmd # draft
        - categorical-glmm.qmd # draft
        - categorical-catboost.qmd # draft
        - categorical-woe.qmd # draft
        - categorical-jamesstein.qmd # draft
        - categorical-mestimator.qmd # draft
        - categorical-thermometer.qmd # draft
        - categorical-quantile.qmd # draft
        - categorical-summary.qmd # draft
        - categorical-collapse.qmd # draft
        - categorical-combination.qmd # draft
        - categorical-multi-dummy.qmd # draft
    - part: "Datetime Features"
      chapters:
        - datetime.qmd # draft
        - datetime-extraction.qmd # draft
        - datetime-advanced.qmd # draft
        - datetime-periodic.qmd # draft
    - part: "Missing Data"
      chapters:
        - missing.qmd # draft
        - missing-simple.qmd # draft
        - missing-model.qmd # draft
        - missing-indicator.qmd # draft
        - missing-remove.qmd # draft
    - part: "Text Features"
      chapters:
        - text.qmd # draft
        - text-manual.qmd # draft
        - text-cleaning.qmd # draft
        - text-tokenization.qmd # draft
        - text-stemming.qmd # draft
        - text-ngrams.qmd # draft
        - text-stopwords.qmd # draft
        - text-filter.qmd # draft
        - text-tf.qmd # draft
        - text-tfidf.qmd # draft
        - text-hashing.qmd # draft
        - text-onehot.qmd # draft
        - text-lda.qmd # draft
        - text-word2vec.qmd # draft
        - text-bert.qmd # draft
    - part: "Periodic Features"
      chapters:
        - periodic.qmd # draft
        - periodic-trig.qmd # draft
        - periodic-splines.qmd # draft
        - periodic-indicators.qmd # draft
    - part: "Too Many Variables"
      chapters:
        - too-many.qmd # draft
        - too-many-zv.qmd # draft
        - too-many-pca.qmd # draft
        - too-many-pca-variants.qmd # draft
        - too-many-ica.qmd # draft
        - too-many-nmf.qmd # draft
        - too-many-pls.qmd
        - too-many-lda.qmd # progress
        - too-many-gda.qmd
        - too-many-autoencoder.qmd
        - too-many-umap.qmd
        - too-many-isomap.qmd
        - too-many-filter.qmd
        - too-many-wrapper.qmd
        - too-many-embedded.qmd
    - part: "Correlated Data"
      chapters:
        - correlated.qmd # draft
        - correlated-filter.qmd # draft
    - part: "Outliers"
      chapters:
        - outliers.qmd # draft
        - outliers-remove.qmd
        - outliers-imputation.qmd
        - outliers-indicate.qmd
    - part: "Imbalanced Data"
      chapters:
        - imbalenced.qmd # draft
        - imbalenced-upsample.qmd
        - imbalenced-rose.qmd
        - imbalenced-smote.qmd
        - imbalenced-smote-variants.qmd
        - imbalenced-borderline-smote.qmd
        - imbalenced-adasyn.qmd
        - imbalenced-downsample.qmd
        - imbalenced-nearmiss.qmd
        - imbalenced-tomek.qmd
        - imbalenced-cnn.qmd
        - imbalenced-enn.qmd
        - imbalenced-hardness-threshold.qmd
        - imbalenced-one-sided.qmd
    - part: "Miscellaneous"
      chapters:
        - miscellaneous.qmd # draft
        - miscellaneous-id.qmd
        - miscellaneous-color.qmd # draft
        - miscellaneous-zipcodes.qmd
        - miscellaneous-email.qmd
    - part: "Spatial"
      chapters:
        - spatial.qmd # draft
        - spatial-distance.qmd
        - spatial-nearest.qmd
        - spatial-count.qmd
        - spatial-query.qmd
        - spatial-embedding.qmd
        - spatial-characteristics.qmd
    - part: "Time-Series Data"
      chapters:
        - time-series.qmd # draft
        - time-series-smooth.qmd
        - time-series-sliding.qmd
        - time-series-log-interval.qmd
        - time-series-missing.qmd
        - time-series-outliers.qmd
        - time-series-diff.qmd
        - time-series-lag.qmd
        - time-series-rolling-window.qmd
        - time-series-expanding-window.qmd
        - time-series-fourier.qmd
        - time-series-wavelet.qmd
    - part: "Image Data"
      chapters:
        - image.qmd # draft
        - image-edge-corner.qmd
        - image-texture.qmd
        - image-grayscale.qmd
        - image-colors.qmd
        - image-noise.qmd
        - image-normalization.qmd
        - image-resize.qmd
        - image-brightness.qmd
        - image-shift-flip-rotate.qmd
        - image-crop-scale.qmd
        - image-embeddings.qmd
    - part: "Ralational Data"
      chapters:
        - relational.qmd # draft
        - relational-manual.qmd
        - relational-auto.qmd
    - part: "Video Data"
      chapters:
        - video.qmd
        - video-tmp.qmd
    - part: "Sound Data"
      chapters:
        - sound.qmd
        - sound-tmp.qmd
    - order.qmd
    - sparse.qmd
    - models.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo.scss, theme.scss]
    include-after-body: [posthog.html, misc.html]
    grid:
      sidebar-width: 350px
pdf:
    documentclass: scrreport
    toc-depth: 1

editor:
  markdown:
    wrap: sentence
    canonical: true
