---
pagetitle: "Feature Engineering A-Z | Periodic Indicators"
---

# Periodic Indicators {#sec-circular-indicators}

::: {style="visibility: hidden; height: 0px;"}
## Periodic Indicators
:::

There will be circular signals that can't be neatly modeled using [sine curves](circular-trig) or [splines](circular-splines).
Our last chance to deal with this type of data is by writing custom indicator functions and applying them.

This chapter is very similar in style to the [Advanced Datetime Features](datetime-advanced) chapter.
With this chapter being the simpler case we don't have to deal with the added complexity that comes with datetime variables.

```{r}
#| label: fig-circular-indicators
#| warning: false
#| echo: false
#| message: false
#| fig-cap: |
#|   Non-trivial activation
#| fig-alt: |
#|   Bar chart. Balues along along the x-axis, numeric effect along the y-axis. 
#|   The activation takes negative values before 0, with larger and larger values
#|   as it gets closer. Only it hits zero it flips and becomes positive, and then
#|   goes back down. 
library(tidyverse)

tibble(
 x = seq(-10, 10),
 activation = case_when(
 x > 0 ~ 5 - sqrt(x) * 2 + x^2 * 0.01,
 x == 0 ~ 5,
 x < 0 ~ -(5 - log(-x + 0.5) * 2),
 )
) |>
  ggplot(aes(x, activation)) +
  geom_col() +
  theme_minimal()
```

Above we see a type of activation we might see in some data.

Creating these features is mostly done by handcrafting.
Making them circular is done using a [modulo](https://en.wikipedia.org/wiki/Modulo) operator,
using the period.

## Pros and Cons

### Pros

- Can capture most a circular signal 

### Cons

- Requires hand-crafted features

## R Examples

## Python Examples
