# Preface {.unnumbered}

Welcome to "Feature Engineering A-Z"! This book is written to be used as a reference guide to all feature engineering methods you will encounter. This is reflected in the chapter structure. Any question a practitioner is having should be answered by looking at the index and finding the right chapter.

Each section tries to be as comprehensive as possible with the number of different methods and solutions that are presented. A section on dimensionality reduction should list all the practical methods that could be used, as well as a comparison between the methods to help the reader decide what would be most appropriate. This does not mean that all methods are recommended to use. A number of these methods have little and narrow use cases. Methods that are deemed too domain-specific have been excluded from this book. 

::: {.callout-note}
# Missing methods

If you think this book is missing a method, then please [file an issue](https://github.com/EmilHvitfeldt/feature-engineering-az/issues/new?assignees=&labels=Request:+New+Method&projects=&template=request-new-method.md&title=) and we will evaluate if it should be added.
:::

Each chapter will cover a specific method or small group of methods. This will include motivations and explanations for the method. Whenever possible each method will be accompanied by mathematical formulas and visualizations to illustrate the mechanics of the method. A small pros and cons list is provided for each method. Lastly, each section will include code snippets showcasing how to implement the methods. This is done in R and Python, using [tidymodels](https://tidymodels.org) and [scikit-learn](https://scikit-learn.org/) respectively. This book is a methods book first, and a coding book second.

::: {.callout-note}
# Empty chapters

A chapter is prefixed with the emoji 🏗️ to indicate that it hasn't been fully written yet.
:::

## What does this book not cover?

- Whole process modeling
- deployment details
- domain-specific methods
- case studies

## Who is this book for?

https://smltar.com/preface#who-is-this-book-for
https://aml4td.org/#intended-audience

## License

https://aml4td.org/#license

## Rendering details

- quarto
- R
- Python
- r packages
- python libraries

## Acknowledgements