[project]
name = "feature-engineering-az"
version = "0.1.0"
description = ""
authors = [{ name = "Emil Hvitfeldt", email = "emilhhvitfeldt@gmail.com" }]
requires-python = ">=3.12,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "scikit-learn>=1.3.2,<2",
    "feazdata==0.0.3",
    "pandas>=2.1.4,<3",
    "feature-engine>=1.9,<2",
    "category-encoders>=2.10,<3",
    "ipykernel>=6.29.2,<7",
    "setuptools>=75.7.0,<76",
    "tensorflow>=2.19.0,<3",
    "imbalanced-learn>=0.14.2,<0.15",
]

[tool.uv]
package = false
